name: Build and push Docker image to Azure Container Registry
'on':
  push:
    branches:
      - main
env:
  DOCKER_REGISTRY: your-azure-container-registry-name.azurecr.io
  DOCKER_IMAGE_NAME: your-docker-image-name
  DOCKERFILE_PATH: path/to/Dockerfile
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: >-
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{github.sha }}
          dockerfile: '${{ env.DOCKERFILE_PATH }}'
        env:
          DOCKER_USERNAME: '${{ secrets.ACR_USERNAME }}'
          DOCKER_PASSWORD: '${{ secrets.ACR_PASSWORD }}'